### ISSUE TITLE
SNOW-1471204: Ability to interpolate variables within `config.toml`

### ISSUE THREAD

**Issue by kameshsampath** [snowflakedb/snowflake-cli#1179]
### Description

When the snow cli creates the `config.toml` it does not interpolate the variables within the attribute values except for `~`.

e.g. 

```toml
default_connection_name="cheatsheets"

[connections]
[connections.cheatsheets]
account = "account-id"
user = "kameshs"
warehouse = "COMPUTE_WH"
schema = "PUBLIC"
authenticator = "SNOWFLAKE_JWT"
private_key_path="$KEYS_DIR/.keys/rsa_key.p8"
```

The `$KEYS_DIR` never gets interpolated while reading the key path.

It will be nice to add variable interpolation support for all attribute values  with in the `config.toml`.
