### ISSUE TITLE
SNOW-1475649: Add --private-key-path option to the toml configuration file

### ISSUE THREAD

**Issue by ATMDawidS** [snowflakedb/snowflake-cli#1192]
### Description

I am able to specify my private key path and authenticator type in the command line using --private-key-path --authenticator SNOWFLAKE_JWT but those option are missing from the toml configuration file

### Context

I will simplify executing, building, testing and deploying my python code to Snowflake

**Comment by sfc-gh-turbaszek** [comment]
It's supported:
```toml
[connections.pkp]
user = "jdoe"
account = "foo"
private_key_path = "/path/to/key.pem"
authenticator = "SNOWFLAKE_JWT"
```
