### ISSUE TITLE
SNOW-1542852: CREATE OR REPLACE when the `runtime` or `execute_as_caller` project file options are changed for a UDF or Stored Procedure during `snow snowpark deploy`

### ISSUE THREAD

**Issue by jhollowell** [snowflakedb/snowflake-cli#1333]
### Description

I would like to force a `CREATE or REPLACE ... ` to be run when the `runtime` or `execute_as_caller` values are modified within a project definition file for a stored procedure or a UDF. I originally thought that's what the `--replace` flag did, but it seems like it tries to be smart and only replace the function if it detects a signature change.

### Context

Currently, when doing a `snow snowpark deploy --replace` command from within a project, if the UDF or Stored Procedure currently exists and the argument signature doesn't change, then the `CREATE or REPLACE ...` command is not run. So if I want to change the runtime or execute_as_caller values, I have to drop the function or stored procedure first and then deploy. For convenience, it would be nice if the CLI did this for me by just running the `CREATE or REPLACE ...`

Here is a sample project file
```yaml
definition_version: 1
snowpark:
  project_name: "my_project"
  stage_name: 'deployment'
  src: "app/"

  procedures:
    - name: my_cool_sproc
      handler: "app_code.handler"
      runtime: "3.10" # I want to be able to change this to 3.11 after already deployed
      signature:
        - name: "arg"
          type: "string"
      returns: variant
      execute_as_caller: True # I want to be able to change this to False after already deployed
```
