### ISSUE TITLE
SNOW-1705656: Lists in mixins get applied twice

### ISSUE THREAD

**Issue by sfc-gh-fcampbell** [snowflakedb/snowflake-cli#1649]
### SnowCLI version

main

### Python version

Python 3.12.3

### Platform

macOS-14.6.1-arm64-arm-64bit

### What happened

Using mixins that contain lists of dicts, like `artifacts`, the list is applied twice. In this minimal example
```yml
definition_version: 2
entities:
  pkg:
    type: application package
    manifest: app/manifest.yml
    meta:
      use_mixins:
        - artifacts_mixin
mixins:
  artifacts_mixin:
    artifacts:
      - src: app/*
        dest: ./
```
The resultant project model is (irrelevant fields omitted)
```yml
definition_version: '2'
entities:
  pkg:
    type: application package
    artifacts:
    - src: app/*
      dest: ./
      processors: []
    - src: app/*
      dest: ./
      processors: []
    manifest: app/manifest.yml
```

I believe this is because `_unique_extend` doesn't properly exclude list items that are dicts when defaults have been added, since the items are no longer identical:
![image](https://github.com/user-attachments/assets/25a078e8-59a1-46e1-a909-b650df659d3d)

### How to reproduce

Evaluate the above snowflake.yml file in a debugger to see that the list is duplicated
