### ISSUE TITLE
Add project definition file schemas

### ISSUE THREAD

**Issue by sfc-gh-vtimofeenko** [snowflakedb/snowflake-cli#2037]
### Description

[JSON Schema Store project](https://www.schemastore.org/json/) provides the format for declaring configuration file schemas. These schemas can be plugged into [editors](https://www.schemastore.org/json/#editors) to provide completion and linting.

[Project definition files](https://docs.snowflake.com/en/developer-guide/snowflake-cli/project-definitions/about) currently:
1. Require having the online documentation open while working on them
2. May be syntactically correct and pass initial validation but Snowflake will refuse to create the object (example below)

<details>
<summary>Sample failing project definition file</summary>

```yaml
definition_version: '2'

mixins:
  snowpark_shared:
    artifacts:
      - dest: my_snowpark_project
        src: app/
    stage: dev_deployment

entities:

  hello_function:
    type: function
    identifier:
      name: hello_function
    handler: functions.hello_function
    signature:
      - name: name
        type: strring  # <--- typo here
    returns: string
    meta:
      use_mixins:
        - snowpark_shared

```

```shell
❯ snow snowpark build && snow snowpark deploy          
Resolving dependencies from requirements.txt
  No external dependencies.
Preparing artifacts for source code
  Creating: app.zip
Build done.
Performing initial validation
Checking remote state
Preparing required stages and artifacts
  Creating (if not exists) stage: dev_deployment
  Uploading app.zip to @DROPME.PUBLIC.dev_deployment/my_snowpark_project/
Creating Snowpark entities
  Creating function hello_function
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 002040 (42601): 01ba115d-0807-3c0f-0057-53030711148a: SQL compilation error:                                                                                │
│ Unsupported data type 'STRRING'.                                                                                                                            │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

</details>

Use cases:

1. Developers using supported editors could iterate on project definition files faster and with lower amount of errors
2. CI/CD pipelines could lint the project definition files early and stop the pipeline if the validation fails
