### ISSUE TITLE
SNOW-2031010: private_key_file_pwd in connections.toml ignored

### ISSUE THREAD

**Issue by Gabriel2409** [snowflakedb/snowflake-cli#2188]
### SnowCLI version

Snowflake CLI version: 3.5.0

### Python version

Python 3.12.5

### Platform

Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35

### What happened

When using the following connections.toml 

```toml
[my_connection]
account = "<MYACCOUNT>"
user = "<MYUSER>"
database = "<MYDB>"
schema = "<MYSCHEMA>"
warehouse = "<MYWAREHOUSE>"
role = "<MYROLE>"
private_key_file = "<path/to/private_key>"
private_key_file_pwd = "<MYPASSPHRASE>"
authenticator = "SNOWFLAKE_JWT"
```

and running `snow connection test -c my_connection`, I get the following error:

`Encrypted private key, you must provide thepassphrase in the environment variable PRIVATE_KEY_PASSPHRASE`. 

However, when using the same connection in snowpark: 

```python
from snowflake.snowpark.session import Session
session = Session.builder.config("connection_name", "met_owner").create()
print(session.sql("SELECT 1").collect())
```
the connection does work. 

Therefore I think it is a problem specific to snowflake-cli. 
From my limited exploration, I think it comes from the _load_pem_to_der function that check that the passphrase is set like this : `private_key_passphrase = SecretType(os.getenv("PRIVATE_KEY_PASSPHRASE", None))`. 

This could be fixed by adding a check on whether private_key_file_pwd exists and use it instead. 

### Console output

```Shell
Encrypted private key, you must provide thepassphrase in the environment variable PRIVATE_KEY_PASSPHRASE
```

### How to reproduce

In connections.toml, add a connection with an encrypted private key and specify the private_key_file_pwd then test the connection.
