### ISSUE TITLE
Support PAT `token` via SNOWFLAKE_ overrides

### ISSUE THREAD

**Issue by kameshsampath** [snowflakedb/snowflake-cli#2288]
### SnowCLI version

Snowflake CLI version: 3.7.2

### Python version

Python 3.11.11

### Platform

macOS-15.4.1-arm64-arm-64bit

### What happened

I am trying to use PAT with Snowflake CLI, the following is the config.toml that can be used with `snow` to connect using PAT 

```toml
[connections]
[connections.default]
account = "my-account"
user = "my-user"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token = "my pat"
```

When I set the `token` using `SNOWFLAKE_TOKEN`, the connection fails as it is not able to load the token.

### Console output

```Shell
nvalid connection configuration. 250001 (08001): None: Failed to connect to DB:                              │
│ account-id.snowflakecomputing.com:443. Programmatic access token is invalid.
```

### How to reproduce

1. Create PAT for an user with authentication policy and network policy.
3. Configure the `config.toml` 
```toml
[connections]
[connections.default]
account = "my-account"
user = "my-user"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token = "my pat"
```
3. Run `snow connection test` 
4. Connection will be successful
5. Now comment the `token` in the `config.toml`
6. export the same token as `SNOWFLAKE_TOKEN`
7. Run Step-3 again, you will see the reported error
