### ISSUE TITLE
SNOW-1209103: Connecting using only env variables doesn't seem to work

### ISSUE THREAD

**Issue by sfc-gh-jhollan** [snowflakedb/snowflake-cli#872]
### SnowCLI version

2.0.0

### Python version

3.10

### Platform

ubuntu x86

### What happened

I'm trying to build a GitHub action that connects using Snowflake CLI. I'm defining these env:

```
env:
  SNOWFLAKE_CONNECTIONS_GH_ACCOUNT: ${{ secrets.ACCOUNT }}
  SNOWFLAKE_CONNECTIONS_GH_USER: ${{ secrets.USER }}
  SNOWFLAKE_CONNECTIONS_GH_PASSWORD: ${{ secrets.PWD }}
  SNOWFLAKE_CONNECTIONS_GH_DATABASE: ${{ secrets.DATABASE }}
  SNOWFLAKE_CONNECTIONS_GH_SCHEMA: ${{ secrets.SCHEMA }}
  SNOWFLAKE_CONNECTIONS_GH_WAREHOUSE: ${{ secrets.WAREHOUSE }}
  SNOWFLAKE_CONNECTIONS_GH_ROLE: ${{ secrets.ROLE }}
  SNOWFLAKE_OPTIONS_DEFAULT_CONNECTION: GH
```

However when the action runs

`snow connection test -c GH` 

The action returns an error "Connection GH is not configured".

I don't really want any config file in a github action, and expected since I'm defining all connection attiritbutes as env that it would still work, but Iw wonder if it still is checking the file first?
