### ISSUE TITLE
SNOW-1259909: Can't create a function/procedure with empty signature

### ISSUE THREAD

**Issue by kokorin** [snowflakedb/snowflake-cli#923]
### SnowCLI version

2.1.0

### Python version

3.9.7

### Platform

Windows-10-10.0.19045-SP0

### What happened

I try to create a procedure with empty signature.

Omitting `signature` property doesn't work
```yaml
definition_version: 1
snowpark:
  project_name: "my_project"
  stage_name: "deployments"
  src: "app/"
  procedures:
    - name: my_procedure
      runtime: "3.10"
      handler: "procedure.do_something"
      returns: string
```

Console output:
```
An unexpected exception occurred. Use --debug option to see the traceback. Exception message:

while parsing a mapping
  in "<unicode string>", line 4, column 1:
      - handler: procedure.do_something
    ^ (line: 4)
required key(s) 'signature' not found
  in "<unicode string>", line 7, column 1:
        runtime: '3.10'
    ^ (line: 7)
```

Null signature doesn't work neither:
```yaml
definition_version: 1
snowpark:
  project_name: "my_project"
  stage_name: "deployments"
  src: "app/"
  procedures:
    - name: my_procedure
      runtime: "3.10"
      signature:
      handler: "procedure.do_something"
      returns: string
```
Console output:
```
An unexpected exception occurred. Use --debug option to see the traceback. Exception message:

when expecting an empty value
found arbitrary text
  in "<unicode string>", line 8, column 1:
        signature: 'null'
    ^ (line: 8)
```

The same for empty array:
```yaml
definition_version: 1
snowpark:
  project_name: "my_project"
  stage_name: "deployments"
  src: "app/"
  procedures:
    - name: my_procedure
      runtime: "3.10"
      signature: []
      handler: "procedure.do_something"
      returns: string
```
Console output:
```
An unexpected exception occurred. Use --debug option to see the traceback. Exception message:

While scanning
  in "<unicode string>", line 8, column 16:
        signature: []
                   ^ (line: 8)
Found ugly disallowed JSONesque flow mapping (surround with ' and ' to make text appear literally)
  in "<unicode string>", line 8, column 17:
        signature: []
                    ^ (line: 8)
```

I checked how SnowCLI creates functions/procedures - it concatenates signature parameter names and types, so I tried a **workaround and did work**:
```yaml
definition_version: 1
snowpark:
  project_name: "my_project"
  stage_name: "deployments"
  src: "app/"
  procedures:
    - name: my_procedure
      runtime: "3.10"
      signature:
        - name: ""
          type: ""
      handler: "procedure.do_something"
      returns: string
```
